### ISSUE TITLE
[FIX] scroll right

### ISSUE THREAD

**Issue by nrpatten** [MPOS/php-mpos#2454]
Fix the scroll right from pushing the user drop down to the right

Add to mpos.css

```css
.navbar-right {
    float: right !important;
    margin-right: 0;
}
```

**Comment by TheSerapher** [comment]
Can you show what exactly is fixed with this? Maybe just two screenshots :-)

**Comment by nrpatten** [comment]
![right](https://cloud.githubusercontent.com/assets/4833541/8650931/97f150c0-29b9-11e5-9ccd-09c71a75e329.jpg)
![no scroll](https://cloud.githubusercontent.com/assets/4833541/8650933/9c597dc2-29b9-11e5-8f3a-79ddd0bd4f1f.jpg)

**Comment by TheSerapher** [comment]
Does that work on all resolutions/devices?

**Comment by nrpatten** [comment]
it should it only takes away margin-right: -14px; that is pushing it over

**Comment by nrpatten** [comment]
another one align worker pass and so on with worker name

mpos.css Line 584 add > `vertical-align: middle;`
```css
.table > tbody > tr > td {
    padding: 4px;
    vertical-align: middle;
}
```
